name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
        
        - name: Use Proxy to SSH and Rsync
  # You may pin to the exact commit or the version.
  # uses: pranksteess/ssh-rsync-action@60dddf2ded2225536e2f70809590bcc0e231e2db
  uses: pranksteess/ssh-rsync-action@v2.1
  with:
    # you know
    rsync_flags: # optional
    # online host
    dst_host: # optional
    # online port
    dst_port: # optional, default is 22
    # online user
    dst_user: # optional
    # 
    proxy_host: # optional
    # 
    proxy_port: # optional, default is 22
    # 
    proxy_user: # optional
    # src file name
    src_file: # optional
    # use the file last build, rsync to proxy host
    cache: # optional
    # temporary save path
    proxy_file_path: # optional
    # online save path
    dst_file_path: # optional
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa
    key: # optional
    # execute commands before rsync on online host
    ssh_before: # optional
    # execute commands after rsync on online host
    ssh_after: # optional
